---
version: '3'

vars:
  LINTER_COMMIT_TARGET_BRANCH: origin/v2
  LINTER_DOCKER_IMAGE: urnai/linter:latest
  PACKAGE_NAME: urnai
  TEST_CONTAINER_NAME: urnai_test
  VIRTUAL_ENVIRONMENT: urnai_env
  DOCKER_URNAI_DIR: /home/mambauser/urnai

env:
  CMD_DOCKER_RUN: docker run --rm
  ROOT:
    sh: pwd
  UID:
    sh: id -u
  GID:
    sh: id -g
  DISPLAY:
    sh: echo $(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):0.0
  LIBGL_ALWAYS_INDIRECT: 1

dotenv:
  - .env

tasks:
  default:
    desc: "List all tasks."
    cmds:
      - task --list-all

  build:
    desc: Builds the Docker image.
    summary: |
      Builds the Docker image.

      Examples:
        - task build
    deps:
      - config-hooks
    cmds:
      - |
        docker build \
          --build-arg UID="$UID" \
          --build-arg GID="$GID" \
          -t {{ .PACKAGE_NAME }} .

  build-no-cache:
    desc: Builds the Docker image without using cache.
    summary: |
      Builds the Docker image without using cache.

      Examples:
        - task build-no-cache
    deps:
      - config-hooks
    cmds:
      - |
        docker build --no-cache \
          --build-arg UID="$UID" \
          --build-arg GID="$GID" \
          -t {{ .PACKAGE_NAME }} .

  config-hooks:
    desc: Configure git hooks.
    summary: |
      Configure git hooks.

      Examples:
        - task config-hooks
    cmds:
      - git config core.hooksPath .githooks

  lint:
    desc: Applies the linters.
    summary: |
      Applies the linters.

      Examples:
        - task lint
    cmds:
      - docker pull {{ .LINTER_DOCKER_IMAGE }}
      - |
        ${CMD_DOCKER_RUN} -v ${ROOT}:/app {{ .LINTER_DOCKER_IMAGE }} " \
          lint-commit {{ .LINTER_COMMIT_TARGET_BRANCH }} \
          && lint-markdown \
          && lint-yaml \
          && lint-shell-script \
          && lint-dockerfile \
          && lint-python ."

  run:
    desc: Runs a specific Python script.
    summary: |
      Runs a specific Python script.

      Arguments:
        CLI_ARGS: Python script path.

      Examples:
        - task run -- ./experiments/solves/collectables_check_env.py
    cmds:
      - |
        ${CMD_DOCKER_RUN} \
          -v ${ROOT}:{{ .DOCKER_URNAI_DIR }} \
          -e WANDB_API_KEY=$WANDB_API_KEY \
          {{ .PACKAGE_NAME }} python {{ .CLI_ARGS }}

  run-ui:
    desc: Runs a specific Python script, but with UI activated.
    summary: |
      Runs a specific Python script, but with UI activated.

      Arguments:
        CLI_ARGS: Python script path.

      Examples:
        - task run-ui -- ./experiments/solves/collectables_check_env.py
    cmds:
      - |
        ${CMD_DOCKER_RUN} \
          -v ${ROOT}:{{ .DOCKER_URNAI_DIR }} \
          -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
          -e DISPLAY=$DISPLAY \
          -e WANDB_API_KEY=$WANDB_API_KEY \
          --net=host \
          {{ .PACKAGE_NAME }} python {{ .CLI_ARGS }}

  shell:
    desc: Runs the container shell.
    summary: |
      Runs the container shell.

      Examples:
        - task shell
    cmds:
      - ${CMD_DOCKER_RUN} -v ${ROOT}:} -it {{ .PACKAGE_NAME }} /bin/bash
      - |
        ${CMD_DOCKER_RUN} -v ${ROOT}:{{ .DOCKER_URNAI_DIR } \
          -u $UID:$GID \
          -it {{ .PACKAGE_NAME }} /bin/bash

  test-coverage:
    desc: Check the test coverage report.
    summary: |
      Check the test coverage report.

      Examples:
        - task test-coverage
    cmds:
      - |
        ${CMD_DOCKER_RUN} \
          -u ${UID}:${GID} \
          -v ${ROOT}:{{ .DOCKER_URNAI_DIR }} \
          {{ .PACKAGE_NAME }} coverage report -m

  unit-test:
    desc: Runs the unit tests.
    summary: |
      Runs the unit tests.

      Examples:
        - task unit-test
    cmds:
      - |
        ${CMD_DOCKER_RUN} -u ${UID}:${GID} -v ${ROOT}:{{ .DOCKER_URNAI_DIR }} \
          --name {{ .TEST_CONTAINER_NAME }} {{ .PACKAGE_NAME }} \
          coverage run -m pytest tests

  test:
    desc: Runs `unit-test` and `test-coverage` commands.
    summary: |
      Runs `unit-test` and `test-coverage` commands.

      Examples:
        - task test
    cmds:
      - task: unit-test
      - task: test-coverage
