---
name: Linting and Unit-test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: urnai/linter:latest
    steps:
      - uses: actions/checkout@v3
      - run: lint-commit

  test:
    name: Run unit tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make build
      - run: make test-coverage
